const abilities = [
  {name: "Animal", img: 'https://wikirby.com/w/images/thumb/a/a1/AnimalKirby.png/250px-AnimalKirby.png'},
  {name: "Archer", img: 'https://wikirby.com/w/images/thumb/f/fe/TD_Archer.png/220px-TD_Archer.png'},
  {name: "Artist", img: 'https://wikirby.com/w/images/thumb/a/a5/Artist.png/250px-Artist.png'},
  {name: "Backdrop", img: 'https://wikirby.com/w/images/thumb/4/47/Backdrop.png/250px-Backdrop.png'},
  {name: "Ball", img: 'https://wikirby.com/w/images/thumb/1/19/Ball_Kirby_NinDL.png/250px-Ball_Kirby_NinDL.png'},
  {name: "Balloon", img: 'https://wikirby.com/w/images/thumb/9/9d/Balloon_Kirby.png/200px-Balloon_Kirby.png'},
  {name: "Beam", img: 'https://wikirby.com/w/images/thumb/f/fc/KF2_Beam.png/300px-KF2_Beam.png'},
  {name: "Beetle", img: 'https://wikirby.com/w/images/thumb/c/c4/TD_Beetle.png/130px-TD_Beetle.png'},
  {name: "Bell", img: 'https://wikirby.com/w/images/thumb/4/49/TD_Bell.png/220px-TD_Bell.png'},
  {name: "Bomb", img: 'https://wikirby.com/w/images/thumb/8/8a/KRTDL_Bomb.png/220px-KRTDL_Bomb.png'},
  {name: "Burning", img: 'https://wikirby.com/w/images/thumb/e/e3/Burning_NinDL.png/250px-Burning_NinDL.png'},
  {name: "Circus", img: 'https://wikirby.com/w/images/thumb/c/c8/TD_Circus.png/220px-TD_Circus.png'},
  {name: "Cleaning", img: 'https://wikirby.com/w/images/thumb/2/2c/Cleaning_Allies.png/250px-Cleaning_Allies.png'},
  {name: "Cook", img: 'https://wikirby.com/w/images/thumb/3/32/Cook_Allies.png/300px-Cook_Allies.png'},
  {name: "Copy", img: 'https://wikirby.com/w/images/thumb/7/75/Copy_kirby.png/250px-Copy_kirby.png'},
  {name: "Cupid", img: 'https://wikirby.com/w/images/thumb/a/a3/Cupid_SqS.png/250px-Cupid_SqS.png'},
  {name: "Cutter", img: 'https://wikirby.com/w/images/thumb/e/e3/KRTDL_Cutter.png/200px-KRTDL_Cutter.png'},
  {name: "Doctor", img: 'https://wikirby.com/w/images/thumb/6/6c/Doctor.png/200px-Doctor.png'},
  {name: "ESP", img: 'https://wikirby.com/w/images/thumb/9/92/ESP.png/250px-ESP.png'},
  {name: "Fighter", img: 'https://wikirby.com/w/images/thumb/a/aa/KRTDL_Fighter.png/250px-KRTDL_Fighter.png'},
  {name: "Fire", img: 'https://wikirby.com/w/images/thumb/8/8e/KRTDL_Fire.png/250px-KRTDL_Fire.png'},
  {name: "Freeze", img: 'https://wikirby.com/w/images/thumb/0/00/Freeze.png/300px-Freeze.png'},
  {name: "Ghost", img: 'https://wikirby.com/w/images/thumb/1/1b/Ghost_Kirby.png/250px-Ghost_Kirby.png'},
  {name: "Hammer", img: 'https://wikirby.com/w/images/thumb/e/e0/Hammer_KF2.png/300px-Hammer_KF2.png'},
  {name: "Hi-Jump", img: 'https://wikirby.com/w/images/thumb/9/93/Hi-Jump_Squeak.png/250px-Hi-Jump_Squeak.png'},
  {name: "Ice", img: 'https://wikirby.com/w/images/thumb/a/a1/KRTDL_Ice.png/250px-KRTDL_Ice.png'},
  {name: "Jet", img: 'https://wikirby.com/w/images/thumb/3/39/Jet_Kirby.png/220px-Jet_Kirby.png'},
  {name: "Laser", img: 'https://wikirby.com/w/images/thumb/8/89/Laser_Squeak.png/300px-Laser_Squeak.png'},
  {name: "Leaf", img: 'https://wikirby.com/w/images/thumb/5/53/KRTDL_Leaf.png/177px-KRTDL_Leaf.png'},
  {name: "Magic", img: 'https://wikirby.com/w/images/thumb/c/c3/KSqSArtMagic.png/300px-KSqSArtMagic.png'},
  {name: "Metal", img: 'https://wikirby.com/w/images/thumb/9/9d/Metal_Kirby.png/220px-Metal_Kirby.png'},
  {name: "Mini", img: 'https://wikirby.com/w/images/thumb/8/8a/KatAMArtMini.png/250px-KatAMArtMini.png'},
  {name: "Mirror", img: 'https://wikirby.com/w/images/thumb/2/23/New_Mirror.png/250px-New_Mirror.png'},
  {name: "Missile", img: 'https://wikirby.com/w/images/thumb/1/13/Missile_KCC_artwork_2.png/200px-Missile_KCC_artwork_2.png'},
  {name: "Needle", img: 'https://wikirby.com/w/images/8/85/Needle-KDDD.png'},
  {name: "Ninja", img: 'https://wikirby.com/w/images/thumb/4/42/KF2_Ninja.png/250px-KF2_Ninja.png'},
  {name: "Parasol", img: 'https://wikirby.com/w/images/thumb/a/a2/KF2_Parasol.png/250px-KF2_Parasol.png'},
  {name: "Plasma", img: 'https://wikirby.com/w/images/thumb/1/18/PlasmaKSSU.png/200px-PlasmaKSSU.png'},
  {name: "Poison", img: 'https://wikirby.com/w/images/thumb/0/05/Poison.png/200px-Poison.png'},
  {name: "Sleep", img: 'https://wikirby.com/w/images/0/03/SleepKirbyPortal.png'},
  {name: "Smash Bros.", img: 'https://wikirby.com/w/images/thumb/e/e3/Final_Cutter.png/300px-Final_Cutter.png'},
  {name: "Spark", img: 'https://wikirby.com/w/images/e/ea/KTD_Spark_artwork.png'},
  {name: "Spear", img: 'https://wikirby.com/w/images/thumb/5/57/KRTDL_Spear.png/200px-KRTDL_Spear.png'},
  {name: "Spider", img: 'https://wikirby.com/w/images/thumb/8/84/Spider.png/250px-Spider.png'},
  {name: "Staff", img: 'https://wikirby.com/w/images/thumb/b/bb/Staff.png/350px-Staff.png'},
  {name: "Stone", img: 'https://wikirby.com/w/images/thumb/5/59/KRTDL_Stone.png/250px-KRTDL_Stone.png'},
  {name: "Suplex", img: 'https://wikirby.com/w/images/thumb/8/82/Suplex_Kirby.png/200px-Suplex_Kirby.png'},
  {name: "Sword", img: 'https://wikirby.com/w/images/thumb/9/9b/KF2_Sword_alt.png/300px-KF2_Sword_alt.png'},
  {name: "Throw", img: 'https://wikirby.com/w/images/thumb/e/e1/Throw.png/300px-Throw.png'},
  {name: "Tornado", img: 'https://wikirby.com/w/images/9/9d/KRtDL_Tornado.png'},
  {name: "UFO", img: 'https://wikirby.com/w/images/thumb/7/77/UFO.png/150px-UFO.png'},
  {name: "Water", img: 'https://wikirby.com/w/images/thumb/7/70/KRTDL_Water.png/250px-KRTDL_Water.png'},
  {name: "Wheel", img: 'https://wikirby.com/w/images/7/7e/WheelKTD.png'},
  {name: "Whip", img: 'https://wikirby.com/w/images/thumb/0/0c/KF2_Whip.png/250px-KF2_Whip.png'},
  {name: "Wing", img: 'https://wikirby.com/w/images/e/e3/KTD_Wing_artwork.png'},
  {name: "Wrestler", img: 'https://wikirby.com/w/images/thumb/2/26/Wrestler.png/250px-Wrestler.png'},
  {name: "Yo-Yo", img: 'https://wikirby.com/w/images/thumb/5/51/Yo-yo_Art_Allies.png/300px-Yo-yo_Art_Allies.png'},
]

const poyo = (msg) => {
  var random = Math.floor(Math.random()*Math.floor(abilities.length));
  var ability = abilities[random];
  msg.author.send(`Kirby Copy Ability: ${ability.name}`, { files: [ability.img] });
}

module.exports = {func: poyo}